==31284== Memcheck, a memory error detector
==31284== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==31284== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==31284== Command: ./build/bin/rmdb test
==31284== Parent PID: 22096
==31284== 
==31284== Warning: set address range perms: large range [0x55f9040, 0x47df9048) (undefined)
==31284== Warning: set address range perms: large range [0x55f9028, 0x47df9060) (noaccess)
==31284== 
==31284== HEAP SUMMARY:
==31284==     in use at exit: 69,525 bytes in 336 blocks
==31284==   total heap usage: 23,141,765 allocs, 23,141,429 frees, 2,617,657,235 bytes allocated
==31284== 
==31284== 40 bytes in 1 blocks are still reachable in loss record 1 of 31
==31284==    at 0x4A390B5: malloc (vg_replace_malloc.c:431)
==31284==    by 0x11E162: start_server() (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11B073: main (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284== 
==31284== 40 bytes in 1 blocks are still reachable in loss record 2 of 31
==31284==    at 0x4A390B5: malloc (vg_replace_malloc.c:431)
==31284==    by 0x11E176: start_server() (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11B073: main (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284== 
==31284== 48 bytes in 1 blocks are still reachable in loss record 3 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x11EC35: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 64 bytes in 1 blocks are still reachable in loss record 4 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x1830FF: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 64 bytes in 1 blocks are still reachable in loss record 5 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x18328E: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 64 bytes in 1 blocks are still reachable in loss record 6 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x18336F: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 72 bytes in 1 blocks are still reachable in loss record 7 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x1831A1: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 72 bytes in 1 blocks are still reachable in loss record 8 of 31
==31284==    at 0x4A3E13B: realloc (vg_replace_malloc.c:1649)
==31284==    by 0x14C9FB: yy_switch_to_buffer(yy_buffer_state*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x14FEF4: yy_scan_bytes(char const*, int) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC86: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 77 bytes in 1 blocks are still reachable in loss record 9 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x4DC54BD: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29)
==31284==    by 0x4DC6E02: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29)
==31284==    by 0x1224AA: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, char const*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E9EC: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 96 bytes in 1 blocks are still reachable in loss record 10 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x1830B1: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 96 bytes in 1 blocks are still reachable in loss record 11 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x183241: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 96 bytes in 1 blocks are still reachable in loss record 12 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x183329: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 104 bytes in 1 blocks are still reachable in loss record 13 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x182731: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 288 bytes in 1 blocks are possibly lost in loss record 14 of 31
==31284==    at 0x4A3DF35: calloc (vg_replace_malloc.c:1554)
==31284==    by 0x40149DA: allocate_dtv (dl-tls.c:286)
==31284==    by 0x40149DA: _dl_allocate_tls (dl-tls.c:532)
==31284==    by 0x4C64322: allocate_stack (allocatestack.c:622)
==31284==    by 0x4C64322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==31284==    by 0x11E358: start_server() (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11B073: main (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284== 
==31284== 336 bytes in 6 blocks are definitely lost in loss record 15 of 31
==31284==    at 0x4A3AB13: operator new[](unsigned long) (vg_replace_malloc.c:714)
==31284==    by 0x1721D7: SmManager::close_db() (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E26E: start_server() (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11B073: main (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284== 
==31284== 512 bytes in 1 blocks are still reachable in loss record 16 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x183120: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 512 bytes in 1 blocks are still reachable in loss record 17 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x1832AF: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 512 bytes in 1 blocks are still reachable in loss record 18 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x183390: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 1,664 bytes in 26 blocks are indirectly lost in loss record 19 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x1830FF: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 1,664 bytes in 26 blocks are indirectly lost in loss record 20 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x18328E: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 1,664 bytes in 26 blocks are indirectly lost in loss record 21 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x18336F: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 1,872 bytes in 26 blocks are indirectly lost in loss record 22 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x1831A1: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 2,496 bytes in 26 blocks are indirectly lost in loss record 23 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x1830B1: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 2,496 bytes in 26 blocks are indirectly lost in loss record 24 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x183241: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 2,496 bytes in 26 blocks are indirectly lost in loss record 25 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x183329: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 2,704 bytes in 26 blocks are indirectly lost in loss record 26 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x182731: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 8,192 bytes in 1 blocks are still reachable in loss record 27 of 31
==31284==    at 0x4A3AB13: operator new[](unsigned long) (vg_replace_malloc.c:714)
==31284==    by 0x11E918: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 13,312 bytes in 26 blocks are indirectly lost in loss record 28 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x183120: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 13,312 bytes in 26 blocks are indirectly lost in loss record 29 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x1832AF: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 13,312 bytes in 26 blocks are indirectly lost in loss record 30 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x183390: Transaction::Transaction(int, IsolationLevel) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x182744: TransactionManager::begin(Transaction*, LogManager*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11E766: SetTransaction(int*, Context*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x11EC72: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== 58,240 (1,248 direct, 56,992 indirect) bytes in 26 blocks are definitely lost in loss record 31 of 31
==31284==    at 0x4A39823: operator new(unsigned long) (vg_replace_malloc.c:472)
==31284==    by 0x11EC35: client_handler(void*) (in /home/pygone/projects/db2023-one/build/bin/rmdb)
==31284==    by 0x4C63608: start_thread (pthread_create.c:477)
==31284==    by 0x4FD2132: clone (clone.S:95)
==31284== 
==31284== LEAK SUMMARY:
==31284==    definitely lost: 1,584 bytes in 32 blocks
==31284==    indirectly lost: 56,992 bytes in 286 blocks
==31284==      possibly lost: 288 bytes in 1 blocks
==31284==    still reachable: 10,661 bytes in 17 blocks
==31284==         suppressed: 0 bytes in 0 blocks
==31284== 
==31284== For lists of detected and suppressed errors, rerun with: -s
==31284== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
